title: LucidSense Documentation
description: LucidSense Documentation!
theme: just-the-docs

url: https://lucidsense.github.io

aux_links:
  Control Panel: https://lucidsense.ai
footer_content: "Copyright &copy; 2025 LucidSense."