title: LucidSense Documentation
description: LucidSense Documentation!
theme: just-the-docs

url: https://docs.sense.lucidstack.xyz

aux_links:
  Control Panel: https://sense.lucidstack.xyz
footer_content: "Copyright &copy; 2025 LucidSense."